### ISSUE TITLE
Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by florestefano1975** [StartHua/Comfyui_segformer_b2_clothes#3]
2024-04-04T10:46:00.433808728Z Traceback (most recent call last):
2024-04-04T10:46:00.433825648Z   File "/workspace/ComfyUI/nodes.py", line 1888, in load_custom_node
2024-04-04T10:46:00.433829178Z     module_spec.loader.exec_module(module)
2024-04-04T10:46:00.433832028Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-04-04T10:46:00.433834799Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-04T10:46:00.433850739Z   File "/workspace/ComfyUI/custom_nodes/Comfyui_segformer_b2_clothes/__init__.py", line 1, in <module>
2024-04-04T10:46:00.433854319Z     from .segformer_b2_clothes import *
2024-04-04T10:46:00.433857299Z   File "/workspace/ComfyUI/custom_nodes/Comfyui_segformer_b2_clothes/segformer_b2_clothes.py", line 19, in <module>
2024-04-04T10:46:00.433860119Z     model = AutoModelForSemanticSegmentation.from_pretrained(model_folder_path)
2024-04-04T10:46:00.433862579Z   File "/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
2024-04-04T10:46:00.433865149Z     return model_class.from_pretrained(
2024-04-04T10:46:00.433867599Z   File "/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2895, in from_pretrained
2024-04-04T10:46:00.433870079Z     state_dict = load_state_dict(resolved_archive_file)
2024-04-04T10:46:00.433872909Z   File "/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 467, in load_state_dict
2024-04-04T10:46:00.433875489Z     with safe_open(checkpoint_file, framework="pt") as f:
2024-04-04T10:46:00.433878010Z safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
2024-04-04T10:46:00.433880660Z 
2024-04-04T10:46:00.434011703Z Cannot import /workspace/ComfyUI/custom_nodes/Comfyui_segformer_b2_clothes module for custom nodes: Error while deserializing header: HeaderTooLarge

**Comment by alexcc4** [comment]
same error

**Comment by alexcc4** [comment]
solved by install git-lfs, and repull the repo:[mattmdjaga/segformer_b2_clothes](https://huggingface.co/mattmdjaga/segformer_b2_clothes)
